version: "3.7"
services:
  mycontainer:
     container_name: mycontainer
     build:
        context: .
        dockerfile: Dockerfile
     network_mode: host
     restart: always
     devices:
        - "/dev/video0:/dev/video0"
     privileged: true
     entrypoint: ["python", "/FlashModel/FlashModel/app.py"]
